from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0004_accessrequest'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='''
                        CREATE TABLE IF NOT EXISTS feedback_requests (
                            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            topic varchar(32) NOT NULL DEFAULT 'question',
                            department varchar(255) NOT NULL DEFAULT '',
                            related_department varchar(255) NOT NULL DEFAULT '',
                            dashboard varchar(255) NOT NULL DEFAULT '',
                            period varchar(120) NOT NULL DEFAULT '',
                            description text NOT NULL,
                            contact varchar(255) NOT NULL DEFAULT '',
                            attachment_names jsonb NOT NULL DEFAULT '[]'::jsonb,
                            status varchar(20) NOT NULL DEFAULT 'new',
                            email_error text NOT NULL DEFAULT '',
                            created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
                            user_id bigint NULL REFERENCES users(id) ON DELETE SET NULL
                        );
                        CREATE INDEX IF NOT EXISTS feedback_requests_user_id_idx
                            ON feedback_requests(user_id);
                    ''',
                    reverse_sql='DROP TABLE IF EXISTS feedback_requests;',
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='FeedbackRequest',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('topic', models.CharField(choices=[('question', 'Вопрос по показателю'), ('bug', 'Сообщить об ошибке'), ('data', 'Проблема с данными'), ('feature', 'Предложение по улучшению')], default='question', max_length=32)),
                        ('department', models.CharField(blank=True, max_length=255)),
                        ('related_department', models.CharField(blank=True, max_length=255)),
                        ('dashboard', models.CharField(blank=True, max_length=255)),
                        ('period', models.CharField(blank=True, max_length=120)),
                        ('description', models.TextField()),
                        ('contact', models.CharField(blank=True, max_length=255)),
                        ('attachment_names', models.JSONField(blank=True, default=list)),
                        ('status', models.CharField(choices=[('new', 'Новое'), ('sent', 'Отправлено'), ('failed', 'Ошибка отправки'), ('completed', 'Выполнено'), ('rejected', 'Отклонено')], default='new', max_length=20)),
                        ('email_error', models.TextField(blank=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_requests', to='User.user')),
                    ],
                    options={
                        'db_table': 'feedback_requests',
                        'ordering': ['-created_at'],
                    },
                ),
            ],
        ),
    ]
