"""
Django settings for Dashbord project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import json
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _env_positive_int(name: str, default: int) -> int:
    try:
        value = int(os.environ.get(name, str(default)))
    except (TypeError, ValueError):
        return default
    return value if value > 0 else default


def _env_bool(name: str, default: bool) -> bool:
    raw = os.environ.get(name)
    if raw is None:
        return default
    return raw.strip().lower() not in {'0', 'false', 'no', 'off'}


_PACKAGE_JSON = BASE_DIR / 'package.json'
with open(_PACKAGE_JSON, encoding='utf-8') as _f:
    _package = json.load(_f)
_db_cfg = _package.get('database', {})

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', _package.get('secretKey', ''))

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'User',
    'getkpi',
    'searchengine',
    'devdir',
    'qualdir',
    'gspp',
    'sup',
    'feedback',
    'autoit',
    'c1auto',
    'tools',
    'aiassistant',
    'lmstudio_proxy',
    'servhead',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Dashbord.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Dashbord.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': _db_cfg.get('name', 'dashbord'),
        'USER': _db_cfg.get('user', 'postgres'),
        'PASSWORD': os.environ.get('DB_PASSWORD', _db_cfg.get('password', '')),
        'HOST': _db_cfg.get('host', 'localhost'),
        'PORT': _db_cfg.get('port', 5432),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

AI_ASSISTANT_PROJECT_ROOT = BASE_DIR.parent
AI_ASSISTANT_AGENT_SRC = BASE_DIR / 'agent' / 'agent' / 'src'
AI_ASSISTANT_MCP_SRC = BASE_DIR / 'agent' / 'MCP' / 'src'
AI_ASSISTANT_MCP_CONFIG = BASE_DIR / 'agent' / 'MCP' / 'mcp_config.json'

# Изолированный OpenAI-совместимый proxy к LM Studio.
LM_STUDIO_BASE_URL = os.environ.get(
    'LM_STUDIO_BASE_URL',
    'http://192.168.1.157:1234/v1',
).rstrip('/')
LM_STUDIO_MODEL = os.environ.get('LM_STUDIO_MODEL', 'qwen3-vl-8b-thinking')
# GGUF embedder (OpenAI-compatible /v1/embeddings). Use LM Studio model key/id
# (HF: Content-AI/USER-bge-m3-Q8_0-GGUF → usually text-embedding-user-bge-m3).
LM_STUDIO_EMBEDDING_MODEL = os.environ.get(
    'LM_STUDIO_EMBEDDING_MODEL',
    'text-embedding-user-bge-m3',
)
LM_STUDIO_API_KEY = os.environ.get('LM_STUDIO_API_KEY', 'lm-studio')
LM_STUDIO_TIMEOUT_SECONDS = _env_positive_int('LM_STUDIO_TIMEOUT_SECONDS', 180)
LM_STUDIO_AUTO_LOAD_MODEL = _env_bool('LM_STUDIO_AUTO_LOAD_MODEL', True)
LM_STUDIO_CONTEXT_LENGTH = _env_positive_int('LM_STUDIO_CONTEXT_LENGTH', 32768)
LM_STUDIO_EMBEDDING_CONTEXT_LENGTH = _env_positive_int(
    'LM_STUDIO_EMBEDDING_CONTEXT_LENGTH',
    8192,
)

# CORS: любой origin (с credentials несовместимо — см. django-cors-headers)
CORS_ALLOW_ALL_ORIGINS = True

# JWT
JWT_SECRET = SECRET_KEY
JWT_ALGORITHM = 'HS256'
JWT_EXPIRATION_DAYS = 7

# Feedback mail transport. Credentials stay on the backend only.
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('DASHBOARD_FEEDBACK_EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('DASHBOARD_FEEDBACK_EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('DASHBOARD_FEEDBACK_EMAIL_USE_TLS', '1') != '0'
EMAIL_HOST_USER = os.environ.get('DASHBOARD_FEEDBACK_EMAIL_USER', 'mangasaryangeneral@gmail.com')
EMAIL_HOST_PASSWORD = os.environ.get('DASHBOARD_FEEDBACK_EMAIL_PASSWORD', 'udhttlogbcmaxebf')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
FEEDBACK_EMAIL_TO = os.environ.get('DASHBOARD_FEEDBACK_EMAIL_TO', 'mangasaryandon@outlook.com')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'getkpi.cache_manager': {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
        'getkpi.views': {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
        'devdir': {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
    },
}
