# Generated by Django 6.0.3 on 2026-04-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('role', models.CharField(choices=[('User1', 'User1 (Admin)'), ('User2', 'User2'), ('User3', 'User3'), ('User4', 'User4'), ('User5', 'User5')], default='User5', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
