# Generated by Django 6.0.1 on 2026-04-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KpiDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(db_index=True, max_length=255, verbose_name='Подразделение')),
                ('kpi_id', models.CharField(db_index=True, max_length=50, verbose_name='Код KPI')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
                ('block', models.CharField(default='плитка', max_length=50, verbose_name='Блок дашборда')),
                ('frequency', models.CharField(blank=True, default='', max_length=100, verbose_name='Периодичность')),
                ('perspective', models.CharField(blank=True, default='', max_length=100, verbose_name='Перспектива')),
                ('goal', models.TextField(blank=True, default='', verbose_name='Управленческая цель')),
                ('formula', models.TextField(blank=True, default='', verbose_name='Формула расчёта')),
                ('unit', models.CharField(blank=True, default='', max_length=50, verbose_name='Ед. изм.')),
                ('source', models.CharField(blank=True, default='', max_length=500, verbose_name='Источник данных')),
                ('monthly_target', models.CharField(blank=True, max_length=100, null=True, verbose_name='Месячная цель')),
                ('quarterly_target', models.CharField(blank=True, max_length=100, null=True, verbose_name='Квартальная цель')),
                ('yearly_target', models.CharField(blank=True, max_length=100, null=True, verbose_name='Годовая цель')),
                ('green_threshold', models.CharField(blank=True, max_length=100, null=True, verbose_name='Зелёный порог')),
                ('yellow_threshold', models.CharField(blank=True, max_length=100, null=True, verbose_name='Жёлтый порог')),
                ('red_threshold', models.CharField(blank=True, max_length=100, null=True, verbose_name='Красный порог')),
                ('weight_pct', models.FloatField(blank=True, null=True, verbose_name='Вес, %')),
                ('chart_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип графика')),
                ('chart_type_label', models.CharField(blank=True, max_length=200, null=True, verbose_name='Подпись типа графика')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'KPI',
                'verbose_name_plural': 'KPI-определения',
                'db_table': 'kpi_definition',
                'ordering': ['department', 'position'],
                'unique_together': {('department', 'kpi_id')},
            },
        ),
    ]
